version: 2.1
orbs:
  eb: circleci/aws-elastic-beanstalk@2.0.1
  node: circleci/node@4.7.0
workflows:
  elastic-beanstalk-workflow:
    jobs:
      - node/test:
          app-dir: ~/Open-Hearts/open-hearts-back-end
      - eb/deploy:
          app-dir: ~/Open-Hearts/open-hearts-back-end
          context: aws-creds
          application-name: Open-Hearts-1
          environment-name: Open-Hearts-1-env
          filters:
            branches:
              only:
                - main
          label: version-<<pipeline.number>>
          requires:
            - node/test
